# Generated by Django 4.0.4 on 2022-05-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0002_alter_videopost_thumbnail_alter_videopost_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='thumbnail',
            field=models.ImageField(default='none', upload_to='videos/thumbnail/'),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='video_file',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
