# Generated by Django 4.0.4 on 2022-05-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0003_alter_videopost_thumbnail_alter_videopost_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sentiment',
            field=models.IntegerField(default=1),
        ),
    ]
