# Generated by Django 4.0.4 on 2022-05-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0004_comment_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='negative_comment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videopost',
            name='positive_comment',
            field=models.IntegerField(default=0),
        ),
    ]
